"""add_agents_table

Revision ID: aed9f12b041f
Revises: 80334deb06fe
Create Date: 2026-02-12 11:33:58.444965

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aed9f12b041f"
down_revision: Union[str, Sequence[str], None] = "80334deb06fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("voice", sa.String(), nullable=True),
        sa.Column(
            "handoff_targets", sa.ARRAY(sa.Uuid()), server_default="{}", nullable=True
        ),
        sa.Column("tools", sa.ARRAY(sa.String()), server_default="{}", nullable=True),
        sa.Column(
            "modality",
            sa.Enum(
                "audio_only",
                "audio_camera",
                "audio_screenshare",
                name="agentmodality",
                native_enum=False,
            ),
            server_default="audio_only",
            nullable=False,
        ),
        sa.Column("panels", sa.ARRAY(sa.String()), server_default="{}", nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agents")
    # ### end Alembic commands ###
