"""Add Session fields for token metadata

Revision ID: f433a5cffc1c
Revises: a465b6431c1a
Create Date: 2026-02-13 11:31:07.905504

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f433a5cffc1c"
down_revision: Union[str, Sequence[str], None] = "a465b6431c1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("session_template_id", sa.UUID(), nullable=True)
    )
    op.add_column("sessions", sa.Column("user_id", sa.String(), nullable=True))
    op.add_column("sessions", sa.Column("modality_profile", sa.String(), nullable=True))
    op.add_column(
        "sessions",
        sa.Column("enabled_panels", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "sessions", sa.Column("token_expiry", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_foreign_key(
        None, "sessions", "session_templates", ["session_template_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_column("sessions", "token_expiry")
    op.drop_column("sessions", "enabled_panels")
    op.drop_column("sessions", "modality_profile")
    op.drop_column("sessions", "user_id")
    op.drop_column("sessions", "session_template_id")
    # ### end Alembic commands ###
